config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :days do
  #resources :days, only: [:index, :show] do
    collection do
      get :search
    end

    collection do
      get :mtotal
    end

    collection do
      get :ytotal
    end
    
  end

  #search(科目明細検索)ページを追加
   #collection do
    #get :search
    #post 'days/search'
    #post 'days/searchlist' => "days#searchlist"
  #sublist(科目明細)ページを追加
    #post :sub
    #end
   #resultページを追加
    #collection do
   #get 'daysresult'
   #end

   

    #get 'days/daysubs', to: 'days#daysubs'
    #post 'days/daysubs', to: 'days#daysubslist'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
    
    scope :search, -> (search_params) do

     name_like(search_params[:name])
     .year_like(search_params[:year])
     .month_like(search_params[:month]) 
    #行頭の.で繋げている
    end

    scope :name_like, ->(name) { where('name LIKE ?',"%#{name}%")if name.present?}
    scope :year_like, ->(year) { where('year LIKE ?',"%#{year}%")if year.present?}
    scope :month_like, ->(month) { where('month LIKE ?',"%#{month}%")if month.present?}

    #where('search_params[:name] LIKE ?',"%#{search_params[:name]}%") if search_params[:name].present? .where('search_params[:date] LIKE ?',"%#{search_params[:date]}%") if search_params[:date].present? 
 #searchメソッドの定義
   #def self.search(search)
    #if search
        #Day.where("name LIKE ?","%#{search}%")
        #Day.where(name: "%#{search}%").where(date: like = ?, "%#{search}%")
        #Day.where("name = ? AND date LIKE ?" , "%#{search}%" , "%#{search}%")
    #else
        #Day.all
    #end
   #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
    def index
      @days = Day.all.order(year: :desc).paginate(page: params[:page], per_page: 20)
      #@days = Day.search(params[:search])
    end

    def new
        @day = Day.new
    end

    def create
        @day = Day.create(day_params)
        redirect_to days_path
    end

    def edit
        @day = Day.find(params[:id])
    end

    def update
        @day = Day.find(params[:id])
        @day.update(day_params)
        redirect_to days_path
    end

    def destroy
        @day = Day.find (params[:id])
        @day.destroy
        redirect_to days_path
    end

    def search #科目検索
        @search_params = day_search_params
        @days = Day.search(@search_params).paginate(page: params[:page], per_page: 15)
    end

    def mtotal #月間集計
        
         @days = Day.where('year = ? AND month =?', params[:year], params[:month]).group(:name)
         
         @days_total = Day.where('year = ? AND month =?', params[:year], params[:month]).group(:name).sum(:value)
         hash = @days_total
         array = hash.values
         @days_sum = array.sum
         
         
         
    end

    def ytotal #年間集計
        @days = Day.where('year = ?', params[:year]).group(:name)
        @days_total = Day.where('year = ?', params[:year]).group(:name).sum(:value)
        hash = @days_total
        array = hash.values
        @days_sum = array.sum
    end

    

    
    #resultページを追加
    #def result
    #end

    #searchページを追加
    #def search
        #viewのformで取得したパラメータをモデルに渡す
       # @days = Day.search(params[:search])
    #end
    #def searchlist
     #   @days = Day.search(params[:search])
    #end

    #subslistを作成
    #def dayssubslist
        #@days = Day.where('name = ? AND date >= ?',
        #params[:name], params[:date])
        #render 'days/dayssubslist'
    #end

    #def group
     #   @days = Day.group("MONTH(date)").sum(:value)
    #end

     private
      def day_params
       params.require(:day).permit(:year, :month, :name, :value, :detail)
      end

      def day_search_params
        params.fetch(:search,{}).permit(:name, :year, :month, :value, :datail)
      end

    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/edit.html.erb
<header>
<h2 class="kakeitouroku">家計編集</h2>
</header>
    <td><a><%= link_to '＜家計一覧へ＞', days_path %></a><td>
    <td><a><%= link_to "＜科目検索へ＞", search_days_path, data: {"turbolinks" => false} %></a></td>
    <td><%= link_to "＜月間集計表へ＞", mtotal_days_path, data: {"turbolinks" => false} %></td>
    <td><%= link_to "＜年間集計表へ＞", ytotal_days_path, data: {"turbolinks" => false} %></td>

<%= form_for(@day) do |f| %>
    
        <div><%= f.select :year,['2019','2020','2021','2022'],{},{class: 'form_new'} %><%= f.label :年 %>
        
        <%= f.select :month,['1','2','3','4','5','6','7','8','9','10','11','12'],{},{class: 'form_new'} %><%= f.label :月 %></div>
        <div><%= f.label :科目 %>
        <%= f.select :name, [
            '','給与','その他','食費','消耗品','ペット','ま','き',
            'ガス','電気','水道','ドコモ','NTT','生保','損保',
            '仕事関係','教養娯楽','交際','衣料','医療','車関係','税金','雑費','特別'
            ],{},{class: 'form_new'}%></div>
        <div><%= f.label :金額 %>
        <%= f.number_field :value %></div>
        <div><%= f.label :詳細 %>
        <%= f.text_field :detail %></div> 

    <div><%= f.submit '編集' %></div>
<% end %>

  

app/views/days/index.html.erb
  <header>
   <h1 class="pagetitle">家 計 簿</h1>
  </header> 
  <section class="link">
   <tr>
    <td ><%= link_to '＜家計登録へ＞', new_day_path %></td>
   <!--一度で検索できるようにする-->
    <td><%= link_to "＜科目検索へ＞", search_days_path, data: {"turbolinks" => false} %></td>
    <td><%= link_to "＜月間集計表へ＞", mtotal_days_path, data: {"turbolinks" => false} %></td>
    <td><%= link_to "＜年間集計表へ＞", ytotal_days_path, data: {"turbolinks" => false} %></td>
    <a><%= will_paginate @days,previous_label: '＜前ページ',next_label: '次ページ＞' %></a>
   </tr>
 </section>  
  
  
 <table class ="itiran" border="1">
   <caption class="saimoku">家　 計 　細 　目　 一　 覧</caption>
    <thead>
      <tr class="koumoku">
        <th>年</th>
        <th>月</th>
        <th>科目</th>
        <th>金額</th>
        <th>摘要</th>
      </tr>
    </thead>

    <tbody>
      <% @days.each do |day| %>
      <tr>
        <td><%= day.year %></td>
        <td><%= day.month %></td>
        <td><%= day.name %></td>
        <td><%= day.value %></td>
        <td><%= day.detail %></td>
        <td><%= link_to '編集', edit_day_path(day) %></td>
        <td><%= link_to '削除', day_path(day), method: :delete %></td>
      </tr>
      <% end %>
   </tbody>
</table> 

 

app/views/days/mtotal.html.erb
<header>
<h2 class="kakeitouroku">月間集計表</h2>
</header>
<tr>
    <td><%= link_to '＜家計一覧へ＞', days_path %></td>
    <td ><%= link_to '＜家計登録へ＞', new_day_path %></td>
   <!--一度で検索できるようにする-->
    <td><%= link_to "＜科目検索へ＞", search_days_path, data: {"turbolinks" => false} %></td>
  <!--<td><%= link_to "＜月間集計表へ＞", mtotal_days_path, data: {"turbolinks" => false} %></td>-->
    <td><%= link_to "＜年間集計表へ＞", ytotal_days_path, data: {"turbolinks" => false} %></td>
</tr>


<table>
<%= form_tag("/days/mtotal",method: "get") do %>
   
 <div> <select name="year">
  <option value="">選択してください</option>
  <option value="2019">2019</option>
  <option value="2020">2020</option>
  <option value="2021">2021</option>
  <option value="2022">2022</option>
　</select>

<%= label_tag(:year,"年") %></div>

 <div> <select name="month">
  <option value="">選択してください</option>
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
  <option value="4">4</option>
  <option value="5">5</option>
  <option value="6">6</option>
  <option value="7">7</option>
  <option value="8">8</option>
  <option value="9">9</option>
  <option value="10">10</option>
  <option value="11">11</option>
  <option value="12">12</option>
  </select>
<%= label_tag(:month,"月") %></div>

<%= submit_tag("検索") %>
<% end %>
</table>
<table>

</table>

 
<table class="kensaku"border="1">
 <tr>
  <th colspan="2"><%= "#{params[:year]}" %>年
  <%= "#{params[:month]}" %>月</th>
 </tr>

<% @days_total.sort %>
<% @days_total.each do |day_total| %>
  <tr>
  <td><%= day_total[0] %></td>
  <td><%= day_total[1] %></td>
  
    <% end %>
  </tr>
  <td colspan="2">合計<%= @days_sum %></td>
</table>
 
 <!--
 <% @days_total.each do |k,v|%>
  <%= "#{k} = #{v}" %>
 <% end %>
 <%= @days.name%>
 <% @days.each do |day| %>
   <%= @days_total %>
   <% end %>
 -->
 
 

app/views/days/new.html.erb
<header>
<h2 class="kakeitouroku">家計登録</h2>
</header>
    <%= link_to '＜家計一覧へ＞', days_path %>
    <%= link_to "＜科目検索へ＞", search_days_path, data: {"turbolinks" => false} %></td>
    <td><%= link_to "＜月間集計表へ＞", mtotal_days_path, data: {"turbolinks" => false} %></td>
    <td><%= link_to "＜年間集計表へ＞", ytotal_days_path, data: {"turbolinks" => false} %></td>


    <%= form_for(@day) do |f| %>
    <div><%= f.select :year,['2019','2020','2021','2022'],{},{class: 'form_new'} %><%= f.label :年 %>
    
    <%= f.select :month,['1','2','3','4','5','6','7','8','9','10','11','12'],{},{class: 'form_new'} %><%= f.label :月 %></div>
    <div><%= f.label :科目 %>
    <%= f.select :name, [
        '','給与','その他','食費','消耗品','ペット','ま','き',
        'ガス','電気','水道','ドコモ','NTT','生保','損保',
        '仕事関係','教養娯楽','交際','衣料','医療','車関係','税金','雑費','特別'
        ],{},{class: 'form_new'}%></div>
    <div><%= f.label :金額 %>
    <%= f.number_field :value %></div>
    <div><%= f.label :詳細 %>
    <%= f.text_field :detail %></div> 


    <dib><%= f.submit '家計登録' %></div>
<% end %>

app/views/days/search.html.erb
<h2 class="kakeitouroku">科目検索</h2>
<tr>
    <td><%= link_to '＜家計一覧へ＞', days_path %></td>
    <td ><%= link_to '＜家計登録へ＞', new_day_path %></td>
   <!--一度で検索できるようにする-->
   <!--<td><%= link_to "＜科目検索へ＞", search_days_path, data: {"turbolinks" => false} %></td>-->
    <td><%= link_to "＜月間集計表へ＞", mtotal_days_path, data: {"turbolinks" => false} %></td>
    <td><%= link_to "＜年間集計表へ＞", ytotal_days_path, data: {"turbolinks" => false} %></td>
</tr>
    <table>
   <%= form_with(scope: :search, url:search_days_path, method: :get, local: true) do |f| %>
   <div><%= f.label :name, "科目" %>
   <%= f.select :name, [
        '給与','その他','食費','消耗品','ペット','ま','き',
        'ガス','電気','水道','ドコモ','NTT','生保','損保',
        '仕事関係','教養娯楽','交際','衣料','医療','車関係','税金','雑費','特別'
        ],{ include_blank: '選択してください'},{value: @search_params[:name]} %></div>
    <div><%= f.select :year,['2019','2020','2021','2022'],{ include_blank: '選択してください'}, {value: @search_params[:year]}%>
    <%= f.label :year, "年"%></div>
    <div><%= f.select :month,['1','2','3','4','5','6','7','8','9','10','11','12'], { include_blank: '選択してください'},{value: @search_params[:month]}%>
    <%= f.label :month, "月"%></div>
        
    <%= submit_tag '検索', class: "button" %>
    <% end %>
</table>
<a><%= will_paginate @days,previous_label: '＜前ページ',next_label: '次ページ＞' %></a>



<table class="kensaku"border="1">
<% unless @search_params.blank? %>
<tr class="koumoku" >
 <th>年</th>
 <th>月</th>
 <th>科目</th>
 <th>金額</th>
 <th>摘要</th>
 </tr>
    <% @days.each do |day| %>  
     <tr>
      <td><%= day.year %></td>
      <td><%= day.month %></td>
      <td><%= day.name %></td>
      <td><%= day.value %></td>
      <td><%= day.detail %></td>
     </tr>
    <% end %>
   <% end %>
</table>
  

app/views/days/ytotal.html.erb
<header>
<h2 class="kakeitouroku">年間集計表</h2>
</header>
<table>
<tr>
    <td><%= link_to '＜家計一覧へ＞', days_path %></td>
    <td ><%= link_to '＜家計登録へ＞', new_day_path %></td>
   <!--一度で検索できるようにする-->
    <td><%= link_to "＜科目検索へ＞", search_days_path, data: {"turbolinks" => false} %></td>
    <td><%= link_to "＜月間集計表へ＞", mtotal_days_path, data: {"turbolinks" => false} %></td>
 <!--<td><%= link_to "＜年間集計表へ＞", ytotal_days_path, data: {"turbolinks" => false} %></td>-->
</tr>
</table>
<table>
 <%= form_tag("/days/ytotal",method: "get") do %>
    <select name="year">
    <option value="">選択してください</option>
    <option value="2019">2019</option>
    <option value="2020">2020</option>
    <option value="2021">2021</option>
    <option value="2022">2022</option>
    </select>
  <%= label_tag(:year,"年") %>

  <%= submit_tag("検索") %>
 <% end %>
</table>
<table>

</table>

　<table class="kensaku"border="1">
   <tr>
    <td colspan="2"><%= "#{params[:year]}" %>年</td>
   </tr>
 　　<% @days_total.each do |day_total| %>
　<tr>
   <td><%= day_total[0] %></td>
   <td><%= day_total[1] %></td>
    <% end %>
　</tr>
  　<td colspan="2">合計<%= @days_sum%></td>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fight</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/results/index.html.erb
<table>
  <caption>XX年収支一覧</caption>
  <thead>
    <tr>
        <th>科目</th>
        <th>１月</th>
        <th>２月</th>
        <th>３月</th>
        <th>４月</th>
        <th>５月</th>
        <th>６月</th>
        <th>７月</th>
        <th>８月</th>
        <th>９月</th>
        <th>１０月</th>
        <th>１１月</th>
        <th>１２月</th>
        <th>合計</th>
　　 </tr>
　　</thead>

   <tbody>
    <tr>
        <th>給与</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
    </tr>
    <tr>
        <th>その他</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
    </tr>
    <tr>
        <th>収入計</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
    </tr>
    <tr>
        <th>食費</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
    </tr>
    <tr>
        <th>消耗品費</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
    </tr>
    <tr>
        <th>ペット</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
    </tr>
    <tr>
        <th>ま</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
    </tr>
    <tr>
        <th>き</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　   </tr>
    <tr>
        <th>ガス</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　　　</tr>
　　　<tr>
        <th>電気</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　　　</tr>
<tr>
        <th>水道</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
        <th>ドコモ</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
        <th>NTT</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
        <th>生保</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
        <th>損保</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
        <th>仕事</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
        <th>教養娯楽</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
    <th>交際</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
        <th>衣料</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
        <th>医療</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
    <th>車関係</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
    <th>税金</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
    <th>雑費</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
<tr>
        <th>支出合計</th>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
        <td>xx</td>
　</tr>
    </tbody>

    <tfoot>
      <tr>
       <th>差引計</th>
       <td>xx</td>
      </tr>
    </tfoot>
</table>